### ISSUE TITLE
Weird PCA Result

### ISSUE THREAD

**Issue by cuttle-fish-my** [vidit09/domaingen#6]
Hi! Thanks to this great work! I'm quite interested in the PCA visualization result but I encountered a weird problem. I found that under ``eval()`` mode of ``RN101`` based CLIP image encoder, the semantc augmentated feature (offests are extracted from the provided weights) located much far away from the source domain than the real target domain images' feature. The corresponding PCA visualization is shown below:
![myplot](https://github.com/vidit09/domaingen/assets/82512952/0b70c684-efeb-47c9-9fcb-e2243186b237)

I wonder have your ever encounterd this problem?
Thanks in advance and looking forward to your replay!

**Comment by vidit09** [comment]
Hello,
Thank you for your interest in our work. Yes the estimated features will not be exactly the same as the actual image features because of the [modality gap](https://arxiv.org/abs/2203.02053) but what we are interested in is the relative configuration of the features w.r.t day image features. We use cosine distance for all the losses, hence the relative distance is preserved i.e. cos(night-image-features ,  night-aug-features) > cos(night-image-features ,  fog-aug-features), for example. 
Hope this helps.
